### ISSUE TITLE
Observe changes in computed styles via MutationObserver?

### ISSUE THREAD

**Issue by surma** [whatwg/dom#1041]
(This issue might be filed in the completely wrong place. I’m not 100% sure where it should live.)

THe most recent interation of the [Container Queries spec](https://drafts.csswg.org/css-contain-3/#typedef-style-query) specifies a new syntax that not only allows you to query a container’s size, but also its computed style. For example:

```css
@container (color: red) {
  h1 {
   /* only applies if the container’s computed style value for `color` is `rgb(255, 0, 0)`. */
  }
}
```

As of now, there is no way to observe computed style changes via JS, which would be required to efficiently polyfill this feature. As I am working on a [container query polyfill](https://github.com/GoogleChromeLabs/container-query-polyfill/), this is relevant to my interest. 

Would `MutationObserver` be a good fit to observe computed style changes?

**Comment by annevk** [comment]
No, you'd want something dedicated in CSSOM for this. Mutation observer is only good for node tree mutations and the computed style can change due to changes outside of that. I recommend opening an issue at https://github.com/w3c/csswg-drafts/issues/new for discussion. (Or perhaps they already have one, haven't checked.)

**Comment by surma** [comment]
Thanks for the explanation. Will pursue that!
