### ISSUE TITLE
Undeprecate document.all

### ISSUE THREAD

**Issue by jfbrennan** [whatwg/dom#1196]
I recently discovered `document.all` in an effort to find more direct ways of referencing elements with an id attribute, like `window.myElementId` apparently works. 

Anyway, I was disappointed to read that `document.all` is deprecated (https://developer.mozilla.org/en-US/docs/Web/API/Document/all) despite being supported by all current versions of major browsers.

I'm not sure of any costs or legitimate issues with using `document.all`, but the DX is awesome:
```
<span id="welcomeMessage" hidden>Welcome!</span>

document.all.welcomeMessage.hidden = false;
document.getElementById('welcomeMessage').hidden = false;
```
What's the harm with un-deprecating this property? #221 appears to be more or less okay with it 🤷‍♂️

**Comment by bathos** [comment]
The [`document.all` attribute](https://html.spec.whatwg.org/#dom-document-all) and the [`HTMLAllCollection` interface](https://html.spec.whatwg.org/#the-htmlallcollection-interface) are defined by the HTML spec, not the DOM spec. You will likely find more background and history there.

The `getElementById` method is safer (it will never return an `HTMLCollection` instead of an `Element`), more robust (consider the collisions that occur for ID values such as “__proto__”, “hasOwnProperty”, or even — given its own indexed access logic — “0”), and far less complicated.

**Comment by jfbrennan** [comment]
Ah I see. If you did unfortunately have multiple elements with the same id then you get `HTMLCollection` not `Element`. Seems quite easy for a reasonable developer to avoid that as well as avoid accessing those other fields. 

I'll move this to the HTML repo, thanks!

**Comment by dtmilonga1982-boop** [comment]
Duplicate of #https://github.com/mdn/browser-compat-data/issues/30340
