### ISSUE TITLE
rename before() and after() of ChildNode

### ISSUE THREAD

**Issue by WesNetmo** [whatwg/dom#134]
https://dom.spec.whatwg.org/#childnode

I really dislike those method names. There must be something better. (Afaik they aren't shipping in any browser yet.)
How about:
fitBefore
pushBefore

Sorry for ruining your sunday.

**Comment by domenic** [comment]
They are already shipping in Firefox. And personal dislike is not enough to change years of established tradition.

**Comment by WesNetmo** [comment]
The tradition is? jQuery? since when jQuery has good naming? I asked several people, some of them are even involved with w3c, none of them could guess what those methods do. In firefox they are not even available in nightly yet.

**Comment by domenic** [comment]
You're right, I was fooled by GitHub's polyfill; Firefox does not implement them. Regardless, these are good names. I'm also not sure what you think the W3C has to do with anything.

**Comment by WesNetmo** [comment]
I just meant that i asked to very skilled people. And sorry but they aren't good names.

**Comment by MadaraUchiha** [comment]
I tend to agree with @WesNetmo here. Function and method names should intuitively be verbs/actions. `insertBefore()` and `insertAfter()` sound far better to me than `.before()` and `.after()`.

**Comment by travisleithead** [comment]
FWIW I like the names. To your point, these APIs must operate on a tree, so there's always a question of "before what?" and "after what?". The same questions could be said of insertBefore from a DOM newbie. I use the following logic to figure it out.
1. before = insertBefore, ergo after = "insertAfter"... i.e. a sibling operation.
2. append = appendChild, ergo prepend = "prependChild" a child list operation.

*if* I was considering an alterative short name, I might be inclined towards "next" and "previous" due to their similarity to nextSibling and previousSibling--unfortunately those names are probably also confusing in their own way, not to mention that "next" runs into problems with iterators...

**Comment by WesNetmo** [comment]
The problem is that `next`, `previous`, `before` and `after` aren't verbs.

These names historically return booleans. I read `sibling.after(otherSibling)` as `sibling.isAfter(otherSibling)`

Would it be too bad to have `putBefore`, `putAfter` instead? They are nearly as short and they make more sense.

**Comment by MadaraUchiha** [comment]
That would be confusing with `insertBefore`, at a glance, what's the
difference between `insertBefore` and `putBefore`? Perhaps
`insertBeforeSibling` or something of that sort?

**Comment by ArkadiuszMichalski** [comment]
Can anyone confirm that this method was already shipped in WebKit (https://bugs.webkit.org/show_bug.cgi?id=74648)? And one more thing, If yes then we have `ChildNode.replace()` or `ChildNode.replaceWith()`?

**Comment by annevk** [comment]
They are not yet in shipping Safari, but I assume they are in nightly. And from that bug it seems they went with `replaceWith()`. Anyway, sorry @WesNetmo, we are not changing these names. They have established themselves in the developer community through libraries and we have gotten plenty of feedback that brevity is important.

**Comment by WesNetmo** [comment]
It's okay, I guess.

<img src="https://imgs.xkcd.com/comics/standards.png">

Have a good 2016 everyone!

**Comment by annevk** [comment]
I don't understand how that comic applies in this situation. Anyway, happy new year to you too!
