### ISSUE TITLE
List subclasses explicitly or not

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#190]
@hayatoito raised this in https://github.com/whatwg/dom/commit/b2ee400a6542dc76d41bed5d2edb8c85ba241bfc. Filing so I don't forget.

Currently we list Text, ProcessingInstruction, Comment, explicitly, rather than simply stating CharacterData. Should we do the same for DocumentFragment and ShadowRoot, or is that case different because DocumentFragment is not an abstract interface?

We should probably treat that case different, since otherwise we'd have to list HTMLMarqueeElement and friends too. However, if we change this, perhaps it makes sense to just use abstract interfaces when they make sense?

@domenic had opinions here too I believe.

**Comment by domenic** [comment]
I don't think this is worth stressing over very much.

I'd say that the intent is that objects with the given brand are called nodes. As such I guess ShadowRoot is redundant with DocumentFragment, although not really in a bad way. Maybe change it to "DocumentFragment (including ShadowRoot)" or something.

But CharacterData might not be right, since if somehow a bare CharacterData object were constructed, it shouldn't count as a Node. On the other hand maybe it's fine to say CharacterData since as long as no specs create CharacterData instances we'll be safe.

**Comment by hayatoito** [comment]
> I don't think this is worth stressing over very much.

Yeah,  I do not have an intention to stress this too much. Either is okay to me.
