### ISSUE TITLE
{{ }}s are showing up in the output

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#22]
See e.g. https://dom.spec.whatwg.org/#interface-childnode:

> node . {{before(nodes)}}

Presumably this was supposed to be some sort of auto-link. Happens all over the place.

**Comment by tabatkins** [comment]
Figured it out - the `{{foo}}` shorthand can't contain markup.  All the ones that are showing up have `<var>` in them.

Either we can just remove the markup (not really necessary) or I can move the `{{foo}}` handling to be text-based, rather than markup-based. I try to minimize the number of text-based transforms, because it's easier for them to misfire and do weird things.

**Comment by annevk** [comment]
So the markup is `<var>` to annotate parameters. I would be okay with deferring to Bikeshed for their representation.

**Comment by tabatkins** [comment]
Cool. Just remove all the `<var>s`, then, and it'll work.

**Comment by domenic** [comment]
Still a number of them present if you CTRL+F for "{{"
