### ISSUE TITLE
Remove "svgevent" and "touchevent" from createEvent list?

### ISSUE THREAD

**Issue by zcorpan** [whatwg/dom#227]
333b03cf6454e803d6433673c33f1292821dac0a added "touchevent" per Web compat research in https://www.w3.org/Bugs/Public/show_bug.cgi?id=25491#c7

https://github.com/whatwg/dom/pull/220 added "svgevent". Was it added because it was supported in Gecko and IE11? @ayg

According to the data in https://github.com/whatwg/html/issues/1054#issue-148590884 right now WebKit/Chromium/Gecko/Edge throw for `TouchEvent` and WebKit/Chromium/Edge throw for `SVGEvent`.

**Comment by ayg** [comment]
At least based on Gecko source code, TouchEvent seems to be behind a pref: http://hg.mozilla.org/mozilla-central/file/1f16d3da9280/dom/events/EventDispatcher.cpp#l923  Maybe other engines also?

There was a problem in my testing methodology, because I grepped the output of http://w3c-test.org/dom/nodes/Document-createEvent.html but it previously omitted the trailing "s" from some of the plurals.  Chrome and Firefox support "SVGEvents", but only Firefox supports "SVGEvent".  New list:

```
AnimationEvent
BeforeUnloadEvent
CloseEvent
CompositionEvent
DeviceMotionEvent
DeviceOrientationEvent
DragEvent
ErrorEvent
FocusEvent
HashChangeEvent
IDBVersionChangeEvent
MutationEvent
MutationEvents
PageTransitionEvent
PopStateEvent
ProgressEvent
StorageEvent
SVGEvents
SVGZoomEvent
SVGZoomEvents
TextEvent
TrackEvent
TransitionEvent
WebGLContextEvent
WheelEvent
```

Exact methodology:

1) For each browser, copy-paste output of http://w3c-test.org/dom/nodes/Document-createEvent.html to a text file, grep for '^Fail.*NOT_SUPP', s/^[^"]*"//, s/".*//.  This gives a list of all the events that are not per the current version of the file.

2) cat chrome.txt firefox.txt ie.txt | sort | uniq -c | sort -nr | grep '^ *[23]' | sed 's/^ *[2-3] //' | sort

The only difference I see is SVGEvent -> SVGEvents.

**Comment by zcorpan** [comment]
Thanks!

Yeah, it seems likely `TouchEvent` is conditional on whether touch is enabled. Confirmed with http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4077 on Opera for Android and Android Chrome.

Maybe the spec should require conditionalness for "touchevent"... (I can submit a PR for this.)

**Comment by zcorpan** [comment]
Related https://github.com/w3c/touch-events/issues/29

@RByers thoughts on this? If there's no `initTouchEvent` maybe all browsers should remove "touchevent" from `createEvent` also? Or is there some reason it's needed for `createEvent`?

**Comment by zcorpan** [comment]
I suppose a possibility is that sites try `createEvent('TouchEvent')` as a way to check whether touch events are supported.

**Comment by zcorpan** [comment]
Quick search in httparchive reveals such usage, e.g.:

http://www.15min.lt/
```js
touch: (function(){
				try { 
					document.createEvent('TouchEvent');
					return true;
				} catch(e) { 
					return false;
				}
			})()
```

http://www.cnbc.com/
```js
var isMobile=(function(){var mobile=false,evt;try{evt=document.createEvent('TouchEvent');mobile=true;}catch(e){}
return mobile;}());
```
