### ISSUE TITLE
Figure out how listeners should fire AT_TARGET when doing retargeting

### ISSUE THREAD

**Issue by smaug----** [whatwg/dom#237]
There are few different options when listeners on non-deep target could fire.

(1) Gecko has traditionally fired listeners this way for XBL and such:
capturing listeners, capturing listener on non-deep-target, capturing listeners in shadow content capturing and bubble listeners on shadow-target, bubble listeners in shadow content, bubble listeners on non-deep-target, bubble listener 
That does differentiate capturing and bubble listeners at target phase when the .currentTarget there is a shadow host. But it keeps the algorithms rather easily understandable. There just is internal phase for the event and listeners are called based on that.
FWIW, Gecko uses this also for input elements and such where the implementation of the element is effectively a native shadow DOM thingie  (native anonymous content in Gecko terms)

(2) Other option is to call both capturing and bubble listeners during capture phase before entering shadow content. That gives non-shadow listeners priority over the listeners in shadow DOM.

(3) Same as (2) but call the listeners at target during bubble phase, when the listeners in shadow DOM has been called already.

I don't like (2).
(1) gives kind of best of both setups (2) and (3) depending on whether light DOM uses capturing or bubble listeners, but it makes the existence of shadow dom sort of visible, since the listeners at target aren't called in the order they were registered, but in the order they were registered for capture or non-capture phase. 
I think I could live with (3) too.

**Comment by smaug----** [comment]
Btw, the setup in Gecko doesn't need to keep any additional state. It is just that event.target returns at_target when the internal phase is at_target or currentTarget == target;

**Comment by annevk** [comment]
We could also always call capture listeners before bubble listeners. I'm not sure how compatible that would be, but at least it wouldn't make shadow trees detectable through a simple trick.

**Comment by annevk** [comment]
It would also be weird to end up in a situation where user agent shadow trees do this differently from content shadow trees I think.

**Comment by smaug----** [comment]
Well in Gecko UA shadow trees follow the normal Gecko model (and yes, that is against the current DOM spec).

**Comment by annevk** [comment]
@rniwa @hayatoito @RByers @dominiccooney would really appreciate feedback on this and https://github.com/w3c/webcomponents/issues/485 as they're blocking specifying the event dispatch model that takes shadow trees into account. That in turn is blocking defining how e.g., `<script>` works in shadow trees since its `load` event needs to be scoped. (See https://github.com/whatwg/html/pull/1100 for the specifics of that.)

**Comment by hayatoito** [comment]
Could you help me to understand the point? I have tried to understand the comments in this issue and w3c/webcomponents#485. I am wondering:

1. The point is how we can update the DOM Standard clearly, without changing the semantics in the current Shadow DOM spec?
2. Or, you have found the ambiguous part in the current Shadow DOM spec?
3. Or, you are proposing the behavior change?

Maybe some of them are being mixed, I guess.

**Comment by annevk** [comment]
Well, I don't really know how the Shadow DOM specification deals with any of this. As I tried to say before, it's not super clear what it's processing model should be. So I suppose it's a mixture of all three your points.

**Comment by RByers** [comment]
@tkent-google and @dtapuska may have more context in this area than me.

**Comment by rniwa** [comment]
So the question here is in what order capturing listeners and bubble listeners are called?  And @smaug---- is suggesting the following order in (1):
1. Capturing listeners outside shadow (i.e. component users)
2. Capturing listeners inside shadow
3. Bubble listeners inside shadow
4. Bubble listeners outside shadow

I don't quite understand the distinction between "bubble listeners on non-deep-target" and "bubble listener".  What does the latter refer to?  Could you clarify?

**Comment by smaug----** [comment]
The question is just about when to call the listeners on shadow host. I think (3) is the way to go, and not (1), even though that complicates Gecko's code a bit, since XBL1 needs (1).
But @annevk  wrote different kind of algorithm, which was (2), in https://github.com/w3c/webcomponents/issues/485

**Comment by rniwa** [comment]
Oh I see. I have to check with my colleagues but (3) makes sense to me.

**Comment by hayatoito** [comment]
See the following issues for the history:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=15543
https://www.w3.org/Bugs/Public/show_bug.cgi?id=21404

https://www.w3.org/Bugs/Public/show_bug.cgi?id=21404#c10 is what the spec defines.
Blink implements this.

**Comment by annevk** [comment]
Thank you @hayatoito. Having read through those it sounds like Shadow DOM means to define 3 from the options @smaug---- lists above. The rationale is that normally event listeners are bubbling listeners and therefore the expectation is that events go from innermost to outermost.

My proposal has 2 for the same reason @hayatoito originally went with 2, but that is easy to fix.

Approach 1 is a split approach. On the way down, only invoke capturing listeners for the targets, on the way up, only invoke bubbling listeners for the targets. Since both capturing and bubbling listeners run on targets, you can technically divide them like this and it seems Gecko does this (including for user agent shadow trees). The downside of this approach is that you can detect whether an element is a shadow host. I think therefore we should not go with it.

**Comment by annevk** [comment]
Unless you tell me otherwise while I sleep later today, I plan on preparing a pull request for 3 tomorrow. I'd like to make some progress here.

**Comment by hayatoito** [comment]
Sorry for the late reply. Yeah, (3) looks same to what Shadow DOM spec defines.
It sounds that we all can agree on (3).
