### ISSUE TITLE
surroundContents() with CharacterData node as newParent argument

### ISSUE THREAD

**Issue by triple-underscore** [whatwg/dom#250]
https://dom.spec.whatwg.org/#dom-range-surroundcontents

It seems strange that Range.surroundContents() doesn't throw an error at step 2, if newParent is a CharacterData node.
In that case, the algorithm will insert newParent into the Range obejct
(step 5: "Insert newParent into context object."),
and then throws an error at the next step ( "Append fragment to newParent." )

Is it intentional?

**Comment by annevk** [comment]
In the source of the document (`dom.bs`) there is this comment by @ayg:

> But for Comment, Text, and ProcessingInstruction, we just fall through
 and throw a HIERARCHY_REQUEST_ERR when we try appendChild(). This makes
 absolutely no sense, but it's what DOM 2 Range specifies, and it's what
 IE9, Chrome 12 dev, and Opera 11.00 implement. Firefox 4.0 only throws
 INVALID_NODE_TYPE_ERR on DocumentFragments, it falls through to
 HIERARCHY_REQUEST_ERR for Documents and DocumentTypes.
>
> Firefox 4.0 does this check later on, so it will do DOM mutations of some
 type if passed a DocumentFragment. We match IE9, Chrome 12 dev, and Opera
 11.00 in doing the check early.
>
> If newParent is a Document/DocumentType/DocumentFragment, and some node is
 also partially contained, DOM 2 Range doesn't say whether to throw
 BAD_BOUNDARYPOINTS_ERR or INVALID_NODE_TYPE_ERR. IE9 and Chrome 12 dev
 throw INVALID_NODE_TYPE_ERR, while Firefox 4.0 and Opera 11.00 throw
 BAD_BOUNDARYPOINTS_ERR. I chose the latter because it's the first thing I
 happened to write down and it makes no real difference, with the even
 split.

So I think it is, even though it's somewhat illogical.

**Comment by triple-underscore** [comment]
Thanks for your reply. I understand. (I missed to read the dom.bs comment.)

**Comment by annevk** [comment]
I should probably add a visible note since it's somewhat weird and might create confusion for others too.

**Comment by ayg** [comment]
For the record, all these notes were originally visible in the spec collapsed at the side, which is a feature I liked in my spec because it addresses questions like this, but everybody else seems to like to put rationale in the source or omit it entirely.
