### ISSUE TITLE
toggleEventListener

### ISSUE THREAD

**Issue by caub** [whatwg/dom#251]
On the same principle than `classList.toggle(clsName [, force])`, `Element.prototype.toggleEventListener(evtName, cb [, force])` could be interesting in my opinion, if it doesn't just make the dom heavier

**Comment by dmethvin** [comment]
What are the semantics of that? Will it toggle the `cb` regardless of capture/bubble flag and other event options? What options would it use if the listener was never there?

**Comment by annevk** [comment]
Also, is there any library precedent for this?

**Comment by cauburtin** [comment]
I don't think so.

yes I forgot the useCapture argument. I wrote something like:

let dropdownToggle = ({currentTarget})=>{
	let toggle = (b=!currentTarget.classList.contains('selected')) => {
		if (b){
			document.addEventListener('mousedown', closeOnOut);
			document.addEventListener('keydown', closeOnEscape);
		} else {
			document.removeEventListener('mousedown', closeOnOut);
			document.removeEventListener('keydown', closeOnEscape);
		}
		currentTarget.classList.toggle('selected', b);
	}, closeOnOut = e => {
		if (!currentTarget.parentNode.contains(e.target)){
			toggle(false);
		}
	}, closeOnEscape = e=> {
		if (e.keyCode===escapeKey){
			toggle(false);
		}
	};

	toggle();
};

**Comment by dmethvin** [comment]
I don't know of any analogy in a library. This API would need all of the arguments that `addEventListener` needs since it's potentially calling both add and remove. The analogy to `classList` isn't good because 1) that case is just toggling a simple string, there is no other associated state, and 2) unlike `classList.contains()`, there is no method exposed to determine whether any event listener is currently attached at all, much less attached with a specific handler and set of event options.

**Comment by domenic** [comment]
What is the use case for this? The OP only contains "on the same principle as classList." But toggling a class has real-world uses, whereas I can't imagine any for toggling an event listener. Has anyone ever written code that does?

**Comment by annevk** [comment]
@caub I recommend reading through https://wiki.whatwg.org/wiki/FAQ#Is_there_a_process_for_adding_new_features_to_a_specification.3F. That FAQ in general has some good information on how to further standards. Thanks!
