### ISSUE TITLE
Is document.createEvent("progressevent") really useful?

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#289]
Is document.createEvent("progressevent") really useful?

The DOM specification says this should be supported:
https://dom.spec.whatwg.org/#dom-document-createevent

However, I don't think this is really useful given that ProgressEvent does not have an initProgressEvent() operation:
https://xhr.spec.whatwg.org/#interface-progressevent

**Comment by cdumez** [comment]
FYI, it seems Firefox and Safari do not support this.

Chrome supports document.createEvent("ProgressEvent") but not document.createEvent("progressevent"). Chrome does not have a ProgressEvent.initProgressEvent() operation.

**Comment by annevk** [comment]
This was done as part of 9e3ce67c7927d6642646a3d0c84fa6d8f7926cfa by @ayg.

@foolip what do you think about removing `ProgressEvent` from `createEvent()`?

**Comment by foolip** [comment]
https://crbug.com/569690 is tracking cleaning up this mess in Blink, and in response to this I just sent out a CL to at least stop the propagation of createEvent support for new event interfaces: https://codereview.chromium.org/2210253002/

Thanks to @doomdavve, we have use counters for everything that wasn't already in the spec since before 9e3ce67c7927d6642646a3d0c84fa6d8f7926cfa, see https://www.chromestatus.com/metrics/feature/timeline/popularity/1160 and find the rest in the dropdown.

ProgressEvent is https://www.chromestatus.com/metrics/feature/timeline/popularity/1177 and is low enough that I'd be willing to attempt removal in Blink if that looks like that shortest path to interop.

**Comment by domenic** [comment]
> I just sent out a CL to at least stop the propagation of createEvent support for new event interfaces: 

Gah, thank you!!

**Comment by annevk** [comment]
@foolip did you file a bug for this one yet?

**Comment by annevk** [comment]
I created a PR for web-platform-tests and the DOM Standard.

**Comment by Ms2ger** [comment]
Relevant Gecko bugs:

https://bugzilla.mozilla.org/show_bug.cgi?id=843489
https://bugzilla.mozilla.org/show_bug.cgi?id=1314303

**Comment by foolip** [comment]
I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=703559 and will see about merging both spec and test changes now.
