### ISSUE TITLE
get rid of NonElementParentNode?

### ISSUE THREAD

**Issue by Netmosfera** [whatwg/dom#298]
What is the reason this was introduced?

`element.getElementById("elm")` would be different from `document.getElementById("elm")` as you know, as the former matches "#elm" only if descendant of `element`. Isn't adding this mixin a bit overkill? Isn't it simpler to add `Element.getElementById()` as well?

To put it another way, `element.query("#elm")` is allowed, why so much effort into disallowing `element.getElementById("elm")`?

Forgive me if I said something dumb :P I'm doing my best to understand the new dom spec.
Thank you in advance.

**Comment by annevk** [comment]
There's a note at https://dom.spec.whatwg.org/#interface-nonelementparentnode that explains this, no?

**Comment by Netmosfera** [comment]
maybe, but I don't get it :P

**Comment by annevk** [comment]
Because that is not web compatible…

**Comment by Netmosfera** [comment]
I suppose i need the definition of "web compatible" then.

**Comment by annevk** [comment]
Websites break if we add that feature.

**Comment by Netmosfera** [comment]
Are there websites relying on purpose on element.getElementById() throwing an exception as the method is not defined?

**Comment by annevk** [comment]
Something like that.

**Comment by Netmosfera** [comment]
I don't want to live on this planet anymore.

**Comment by annevk** [comment]
This by far not the worst wart in the platform. 😊

**Comment by Netmosfera** [comment]
fair enough. thanks for the clarifications, though :)

**Comment by MadaraUchiha** [comment]
Please do explain (I'm not sarcastic, I'm actually curious), because I'm having trouble understanding the cause of this too.

Suggesting that people actually use `someElement.getElementById()` and expecting it to throw in normal execution is akin to saying "well, `Number.isNaN` used to throw a TypeError, so we can't use that because someone is relying on that behavior".

It's not normal behavior, it's exceptional, so I don't see how the argument holds. 

As for "there are bigger warts", yes, that's definitely true, how does that diminish the size of *this* wart?

**Comment by domenic** [comment]
It's not an argument, it's an empirical fact. Browsers tried to ship getElementById on Element.prototype, and it broke a decent percentage of popular web sites.

**Comment by Netmosfera** [comment]
out of curiosity too, what were they doing with element.getElementById() ?

**Comment by annevk** [comment]
I think they checked if the method existed on an object and then assumed it was a document. There is probably some pointers in the git log.
