### ISSUE TITLE
Why is the second parameter to MutationObserver.observe() optional?

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#332]
The second parameter to MutationObserver.observe() is optional in the specification. I don't understand why we don't simply mark it as mandatory considering that it will throw a TypeError if omitted anyway.

Behavior of browser engines:
- Gecko agrees with the spec (Argument is optional but throws a TypeError when omitted)
- WebKit / Blink mark the second parameter as mandatory

**Comment by annevk** [comment]
Per IDL you cannot have mandatory dictionaries as final argument. They are treated identically to {}. That is a little weird if the dictionary ends up being effectively required as is the case here, but marking it mandatory doesn't really help us since we still have to handle the {} case anyway.

See https://github.com/heycam/webidl/issues/130 for more discussion.
