### ISSUE TITLE
Consider adding document.parseURL(url)

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#356]
https://github.com/whatwg/url/issues/71 has a long discussion over whether the second argument in `new URL()` should perhaps default to something from the environment. The conclusion from that thread appears to be that it would be better to instead expose a convenience method on the object where that default would come from.

This would basically parse a URL against the base URL of the document.

**Comment by melvyn-sopacua** [comment]
I don't believe we need a parser, URL() should do that. We need a resolver.

How about this:

URL Object
URL(string url, URLResolverInterface Iface=<Implementation specific default object>)
Methods:
bool is_fully_qualified_url(): whether URL contains all information to establish a connection with the server (server being a broad term)
bool is_absolute(): whether URL contains all information to resolve the document path from the root node of the server
bool is_relative(): whether URL contains only parts that can be resolved using a related location

Note: Implementation specific default object should probably be window.location for the browser and that being the window that corresponds with the address bar. For authors it will then be transparent when they need to provide a different resolver.

URLResolverInterface:
string make_fully_qualified_url(): returns fully qualified URL
string make_absolute_url(): returns absolute URL

In the constructor of URL, it calls make_fully_qualified_url() on the provided object, either unconditionally or when it determines the URL is not fully qualified (implementer freedom).
Note that make_absolute_url() should be capable of both expanding a relative URL as well as reducing a fully qualified one.
Protocol-relative URL handling may be needed. I don't see the need for make_relative_url() but others might.

**Comment by annevk** [comment]
There's no way to parse a relative URL (without a base URL) so I'm not sure how that makes sense.

**Comment by melvyn-sopacua** [comment]
On Wednesday 02 November 2016 08:19:05 Anne van Kesteren wrote:
> There's no way to parse a relative URL (without a base URL) so I'm not
> sure how that makes sense.

Leaving protocol-relative out of the discussion for clarity, this would 
be the constructor in pseudo:

    if not has_scheme(url)
        url = IFace.make_fully_qualified_url(url)
    
    parse(url)

It can become smarter if one wants to pass the URL object in a 
preliminary state and make getters/setters verify whether parsing is 
finished, but the procedure remains:

1. Determine whether we have all the info
2. If needed, request needed info from the object adhering to the 
interface
3. Finish parsing with complete info

Maybe you should clarify which cases you are thinking of that make you 
say "no way to parse without base URL", because I can make or find a 
parser that extracts path components just fine from a given string.
I can also determine if a scheme is present, since spec provides a max 
length before which a scheme terminating column must occur and a limited 
character set for the scheme.
-- 
Melvyn Sopacua

**Comment by annevk** [comment]
> I can make or find a parser that extracts path components just fine from a given string

In a web browser?
