### ISSUE TITLE
Consider boolean interface for properties

### ISSUE THREAD

**Issue by jonathanKingston** [whatwg/dom#461]
I often want to control boolean attributes with a property, forgetting that I have to write boiler plate to `setAttribute`/`removeAttribute` when other libraries provide convenience functions that are based upon the type or the attribute being set.

jQuery has two methods `attr()` and `prop()` which make managing boolean attributes much simpler:

```
$el.prop("hidden", true); // <el hidden="" />
$el.prop("hidden", false); // <el />
```

and:
```
$el.attr("hidden", true); // <el hidden="hidden" />
$el.attr("hidden", false); // <el />
```

Perhaps it doesn't make sense to implement this for all attributes, instead provide just:

```
el.setBoolAttribute("");
```

Which would function like:
```
Element.prototype.setBoolAttribute = function (attr, bool) {
  if (bool) {
    this.setAttribute(attr, "");
  } else {
    this.removeAttribute(attr);
  }
};
```

That being said a new `el.prototype.attr()` method could implement this too, where boolean attributes to the second argument would behave different to a string:
```
el.attr("hidden", "false"); // <el hidden="false" />
el.attr("hidden", false); // <el />
```

**Comment by domenic** [comment]
I agree this is something I've wanted for a long time, although properly using reflected properties (like `el.hidden = false`) works pretty well.

If we were to do a new API, my preference would be `el.toggleAttribute(attributeName, bool)` (where if the `bool` is omitted, it toggles it away from its current state).

**Comment by bkardell** [comment]
or maybe borrow from `.classList` and do `toggleAttribute(attr[,force])`?

**Comment by bkardell** [comment]
Would/could this interface be smart about Aria booleans too? The divergence here is something I see people get wrong constantly. I'm not sure that's a good idea or not to try, but maybe worth discussing?

**Comment by domenic** [comment]
Definitely not if in DOM; ARIA booleans probably need an ARIA-specific API.

**Comment by WebReflection** [comment]
There's a parallel world about special attributes exposed through JS via DOM, one is the real hook, usually an accessor in the prototype, and another one is the HTML facade.

My way to understand if a property should be set through `node.setAttribute(key, value)` rather than `node[key] = value;` is to simply feature-detect `key in node ? (node[key] = value) : node.setAttribute(key, value);`.

This works for 99% of special properties, including DOM Level 0 events, but it fails with special attributes like `style`, so far the only one I know, because you cannot `node.style = blah` directly, that's a special setter.

To give you a better understanding of how attributes VS accessors work, check the following example:
```js
document.body.innerHTML = '<input value="123">';
var input = document.body.firstElementChild;

// fallback to attribute
input.value; // 123

// same as
input.getAttribute('value'); // 123

// but look at the screen now ...
input.value = 456;

// there you go, still 123
input.getAttribute('value'); // 123

// outerHTML? Same
input.outerHTML; // <input value="123">

// but what will be submitted ?
input.value; // 456
```

The boolean case is an extra exception to the rule: is it `true` ? Attribute will be there, otherwise it won't.

```js
document.body.innerHTML = '<input value="123">';
var input = document.body.firstElementChild;
input.disabled = true;

// and here the outcome
input.outerHTML; // <input value="123" disabled="">
```

In this case it's just about having such attribute, but it's value is important too.

For strictly boolean defined attributes the value is not relevant, the `boolean` value is define by the presence of such attribute, no matter what's the value!

**However** there are cases where boolean presence can have also meaningful values, which is a whole new world of possibilities.

This is the case of the `crossorigin` [attribute](https://jakearchibald.com/2017/es-modules-in-browsers/#no-credentials), which has a boolean meaning (is it there or not?) and also a possible meaningful value such `use-credentials`.

Here the logic to whatever standard proposal should consider the ability to pass a non boolean, reflected, value.

**Comment by annevk** [comment]
With regards to OP.

A thing we could maybe do is revive `NamedNodeMap` (aka `ele.attributes`) and put a better attribute API there. Although given

```
ele.setAttribute(x, y);
ele.attributes.set(x, y);
```

and the potential savings of not having to allocate such an object if not asked for makes this not worth it. (Main upside I'd see is that we'd make the namespace situation less weird and have a convenient place to put attribute-related functionality. But continuing to use the "Attribute" suffix is probably fine.)

<hr>

With regards to the previous comment.

`<input value>` is reflected by `<input>.defaultValue`, not `<input>.value`. The latter only sometimes matches it as you've experienced (this goes for a number of other attributes too).

It does seem fairly popular in libraries to mix and match DOM attributes and IDL attributes (aka IDL-defined properties / methods), but we never really found a good way to abstract from that. That should probably be a separate discussion though as it's quite a bit different from OP.

**Comment by WebReflection** [comment]
> That should probably be a separate discussion though as it's quite a bit different from OP.

if you read 'till the end you'll see I've passed through `value` and boolean attributes too, ending up with `crossorigin` which is both boolean and meaningful.

I think at least the boolean part, should be compatible with whatever idea comes up, but since in this case an attribute can also have a value, a solution compatible with that case too maybe would be ideal?

As summary, properties used as boolean may also have a value, the OP mentioned interface could probably address these too.

**Comment by rakina** [comment]
If we want this for boolean attributes only, probably `toggleAttribute(attr[,force])` should work just fine? Maybe for cases like setting `crossorigin` to something other than an empty string such as `use-credentials`, `setAttribute` should be used.

**Comment by annevk** [comment]
Yeah, I think that API is the way to go. Would Chrome implement this? Firefox would happily follow suit here I think.

@dstorey would Edge?

**Comment by WebReflection** [comment]
> Maybe for cases like setting crossorigin to something other than an empty string such as use-credentials, setAttribute should be used.

would `toggleAttribute('crossorigin')` put back whatever value was in there, once toggled back?

**Comment by annevk** [comment]
@WebReflection that would make this less straightforward as then you need to keep side-table of those original values. My thinking was that this would solely map to `setAttribute(name, "")` and `removeAttribute(name)`, depending on what `hasAttribute(name)` returns and the value of _force_.

**Comment by WebReflection** [comment]
@annevk to be honest, I don't think it's super important to have that any differently, but if you create template dynamically as with _hyperHTML_ or _lit-html_ (or others) having that ability might simplify things. Worth saying I've personally solved this issue already so I actually would probably never benefit from this method, but others not using _hyperHTML_ but raw DOM might surely appreciate this new method.

If that ever happens please let me know so I can add it to my DOM4 polyfill, thanks.

**Comment by rakina** [comment]
> Would Chrome implement this? 

Yep, we're interested in implementing this.

**Comment by annevk** [comment]
Great, so what we need next is a PR that changes the standard to add this, and a PR in web-platform-tests to test it. If someone would like to take that on it'd be much appreciated!

**Comment by dstorey** [comment]
We're interested in implementing this.

**Comment by jonathanKingston** [comment]
As mentioned @annevk I would like to take writing this up and the testing of it. I can't commit to a time right now however I don't think it should take me too long.

**Comment by jonathanKingston** [comment]
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1469592

**Comment by inexorabletash** [comment]
Update for https://github.com/web-platform-tests/wpt/edit/master/interfaces/dom.idl ?

**Comment by jonathanKingston** [comment]
Ah thanks @inexorabletash will check over https://github.com/jonathanKingston/web-platform-tests/tree/change-interface-toggle later/tomorrow. Thanks!

**Comment by dstorey** [comment]
This is in code review now in Edge. It will be included in an upcoming version.
