### ISSUE TITLE
dispatch algorithm doesn't seem to handle the case when target or relatedTarget is Window object

### ISSUE THREAD

**Issue by smaug----** [whatwg/dom#580]

**Comment by annevk** [comment]
@smaug---- could you please provide more context. What exactly is there to handle?

**Comment by smaug----** [comment]
Things like ''Let relatedTarget be the result of retargeting event’s relatedTarget against target'
where retargeting itself doesn't seem to work with Window.
"If A’s root .." what is Window's root? I couldn't find any definition for that.

**Comment by annevk** [comment]
Thanks. Sounds like https://dom.spec.whatwg.org/#retarget should check if _A_ is a node, first, and return _A_ if not.

And then similar checks in 11.1.3, 11.2, 11.4, and 18.

**Comment by smaug----** [comment]
Are there cases when target is Window, but relatedTarget something in a shadow DOM? Or vice versa

**Comment by annevk** [comment]
Hmm yeah, I'm not sure. Maybe someone from @whatwg/components knows. I vaguely recall a discussion about this before and I'm somewhat surprised it resurfaced.

The other thing I wonder about here is when someone dispatches a synthetic event. Do we assume that in that case relatedTarget the concept is not set, even though the relatedTarget attribute can return something controlled by the developer?

**Comment by hayatoito** [comment]
I remember I have tried to fix compsoedPath() for Window at
https://github.com/whatwg/dom/pull/327, however it wouldn't be enough.

I agree that we have to fix the standard so that we can consider non-node EventTarget nicely.
Basic idea should be:
-  Non-node EventTarget event.target and event.relatedTarget should be visible from anywhere.
-  From Window, any node in a shadow tree shouldn't be visible.
-  From Window, any node in a document tree should be visible.

**Comment by annevk** [comment]
I think I'll try to merge this into #585 since it affects that step too.

**Comment by annevk** [comment]
Pushed a fix for this too.
