### ISSUE TITLE
Editorial: improve clarity in event dispatch model

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#645]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1449560#c5 @bzbarsky wrote:

> In particular, the fact that the "target" in the dispatch algorithm becomes the "item" in the event path structs.

I'd welcome ideas on how to improve this. I agree it's a bit of a mess, but I also don't quite see how to make things substantially better. We could rename to "item" to "current target" perhaps, but I'm not sure if that helps or hurts things.

> I _really_ hope "the last tuple in event’s path whose target is non-null" is in fact the thing that we are thinking of as the target of the event... Is it?

It's the outermost target. The innermost target (the one passed to dispatch) will be the first tuple in event's path whose target is non-null.

**Comment by bzbarsky** [comment]
> I'd welcome ideas on how to improve this.

The issue isn't really what `item` is named in the event path struct.

The issue is that the fact that `target` becomes `item` allows some other thing to become `target`, so that `target` can mean different things depending on where exactly you are looking...

**Comment by bzbarsky** [comment]
One option is to rename `item` to `current target` in the dispatch structs and then rename `target` to `current target` in the algorithm that constructs them, so that the names match....

And maybe call the thing that becomes `target` in the dispatch struct `targetOverride` or `target` consistently?  Less sure about this one.

It would also help a lot if https://dom.spec.whatwg.org/#concept-event-path-append described the meaning of the members of the struct.  Right now nothing seems to do that, so you have to go dig to figure out what the difference is between the `target` and `targetOverride` arguments and when one would use one vs the other.  I _think_ the `target` argument is what will become the event's `currentTarget` when dispatching to this struct and `targetOverride`, if not null, is what retargets the event at shadow dom boundaries?  But I'm not 100% sure that's always the case even after reading through this stuff for a bit and double-checking with smaug.

**Comment by annevk** [comment]
Your understanding is correct and those seem like reasonable suggestions. (We also use `targetOverride` to set `event.target` to document while dispatching on the `Window` object.)
