### ISSUE TITLE
 async disconnectedCallback?

### ISSUE THREAD

**Issue by mkay581** [whatwg/dom#705]
I couldn't find any information in the WebComponents spec about whether `connectedCallback` and `disconnectedCallback` lifecycle hooks support promises or not. But I'd like to do things asynchronously before a component is removed from the DOM. Let's assume I have a custom element that represents a page within my application. I'd like to be able to fade the page out before it disconnects.

```js
 class MyPage extends HTMLElement {
    async disconnectedCallback() {
        const animation = this.animate([
                { opacity: 1},
                { opacity: 0},
            ],
            {
                duration: 1500,
                fill: 'forwards',
            });
        return animation.finished;
    }
  }
```

As of right now, when the element is removed from the DOM, it does not wait for the promise I'm returning, so the fade out never happens.

Here is a working example:
https://stackblitz.com/edit/async-callbacks

**Comment by domenic** [comment]
This isn't possible, because disconnecting something from the DOM is a sync operation, and we can't change that. Tons of code in the world, both in JS and in browser C++, assumes that once you call el.remove(), on the very next line (with no awaiting) the element is disconnected.

Closing since this is not something we can change in the spec, but happy to continue explaining in the closed thread if necessary.
