### ISSUE TITLE
Should adopting change an element's prototype?

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/dom#731]
```js
document.body.append(
  iframe.contentDocument.createElement('p'),
);
```

Will the paragraph have a prototype from the parent or the iframe?

Test: https://static-misc.glitch.me/custom-element-adoption-test/ (see console).

Chrome/Safari leave the prototype as it is.

Firefox/Edge change the prototype to one from the parent page.

Chrome/Safari/Edge change the prototype if the element is a custom element. I assume this is standard, but I haven't yet found it in the spec.

**Comment by annevk** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=20567 has some light reading on part of this topic (tl;dr: no).

The prototype of a custom element can change due to upgrading iirc: https://html.spec.whatwg.org/multipage/custom-elements.html#concept-upgrade-an-element, with the constructor defined at https://html.spec.whatwg.org/multipage/dom.html#htmlconstructor.

**Comment by jakearchibald** [comment]
Thanks for the background!

Ah, I see custom elements are upgraded at insert-time, not adopt-time.

**Comment by jakearchibald** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1470017

Closing, since this is decided.
