### ISSUE TITLE
Reference to struct in inner invoke

### ISSUE THREAD

**Issue by Zirro** [whatwg/dom#738]
>  If struct’s item-in-shadow-tree is false, then set global’s current event to event.

Step 2.8.2 of "[inner invoke](https://dom.spec.whatwg.org/#ref-for-event-path-item-in-shadow-tree%E2%91%A0)" contains a reference to "struct’s" which doesn't seem to be defined within the algorithm. The earlier "invoke" algorithm is given a struct, but it's not clear whether it's passed to "inner invoke".

**Comment by annevk** [comment]
Thank you, this was introduced in https://github.com/whatwg/dom/commit/c69d7c0fb8796de884652c517825122d12901ef5. I guess we need to either pass this on or the value of its item-in-shadow-tree. Since you found it, you get to pick. If you want to fix it that'd be great too, but I'm also happy to do it.
