### ISSUE TITLE
TreeWalker::nextNode() method, loops infinite

### ISSUE THREAD

**Issue by Quetzalfir** [whatwg/dom#787]
https://dom.spec.whatwg.org/commit-snapshots/57512fac17cf2f1c4c85be4aec178c8086ee5ee4/#interface-treewalker

> The nextNode\(\) method, when invoked, must run these steps:​
> 
> 1. Let node be the context object’s current\.
> 2. Let result be FILTER\_ACCEPT\.
> 3. While true:​
>     1. While result is not FILTER\_REJECT and node has a child:​
>         1. Set node to its first child\.
>         2.Set result to the result of filtering node within the context object\.
>         3. If result is FILTER\_ACCEPT, then set the context object’s current to node and return node\.
>     2. Let sibling be null\.
>     3. Let temporary be node\.
>     4. While temporary is non\-null:​
>         1. If temporary is the context object’s root, then return null\.
>         2. Set sibling to temporary’s next sibling\.
>         3. If sibling is non\-null, then break\.
>         4. Set temporary to temporary’s parent\.
>     5. If sibling is null, break
>     6. Set node to sibling
>     7. Set result to the result of filtering node within the context object\.
>     8. If result is FILTER\_ACCEPT, then set the context object’s current to node and return node\.

In the algorithm are missing the steps "V" and "VI", without them, it loops infinite

**Comment by Quetzalfir** [comment]
This is one of the misunderstandings I could find in the reference, however I don't know if there are more details like this. I hope not because I am basing my code completely on this reference.

**Comment by annevk** [comment]
See also #667 and #672. If someone could write the necessary tests to figure out what happens in browsers and adjust the specification accordingly that would be appreciated.

**Comment by pwombwell** [comment]
Using the currently published algorithm, the following web platform tests fail:
dom/traversal-TreeWalker-previousNodeLastChildReject
dom/traversal-TreeWalker-walking-outside-a-tree
dom/traversal-TreeWalker-previousSiblingLastChildSkip
dom/traversal-TreeWalker-traversal-skip (one subtest)

The following tests infinite loop:
web-platform-tests/dom/traversal-TreeWalker-acceptNode-filter
web-platform-tests/dom/traversal-TreeWalker-currentNode
web-platform-tests/dom/traversal-TreeWalker-traversal-reject

Steps 3.2 and 3.3 create variables 'sibling' and 'temporary'. Step 3.4's sub-steps traverse the tree setting sibling and temporary, but their values are never used. Step 3.5 just uses the 'node' value that was set in step 3.1.

If step 3.4.3 is modified to "If sibling is non-null, set node to sibling, then break.", then all the TreeWalker web platform tests pass, including the subtests in acid3.

**Comment by annevk** [comment]
Thank you @pwombwell! Did you also look at https://github.com/whatwg/dom/issues/667#issuecomment-480926881 by any chance?

I tried to come up with a scenario where that would produce different results, but failed. @oozcitak did you think about that at all since then?

Unless someone comes up with a plausible test I'm inclined to take the fix suggested by @pwombwell and move on.

**Comment by pwombwell** [comment]
I'm pretty sure that #667 is identical to my suggested fix. Using the algorithm in #667:
- 3.iv.a checks if it's got to the top of the tree. In this case, sibling must be null. It breaks (goes to step 3.v) which then breaks again (to 4) which returns null. This is the same as the original algorithm which just returns null in step 3.iv.a.

- 3.v checks sibling for null. This line can only be executed if temporary is null (which, without the change to 3.iv.a can't happen since it should hit the root first) or if 3.iv.c has broken. But, in the latter, sibling isn't null so this step would just continue.

- 3.vi sets node to sibling as my suggested fix does a little earlier.

So I think the difference between my suggestion and the suggestion in #667 is just stylistic. #667 doesn't seem to like early returns, whereas the original algorithm returns in the middle of loops.
