### ISSUE TITLE
Specify that AbortController#abort() be bound to AbortController instance

### ISSUE THREAD

**Issue by broofa** [whatwg/dom#981]
The AbortController/Signal pattern is a bit cumbersome to use because it requires referencing the `abort` property through the controller instance.  If `abort()` was bound to the controller it could be destructured immediately upon creation.  For example, take this use case where the `abort()` is delegated to an external control...

```javascript
const abortController = new AbortController();

// delegate abort
$('#someButton').addEventListener('click', () => abortController.abort());

// abortable actions
await someAction();
if (abortController.signal.aborted) throw Error('Aborted');
await otherAction(abortController.signal);

// etc...
```

Making the suggested change would allow for this code, instead...
```javascript
const {signal, abort} = new AbortController();

// delegate abort
$('#someButton').addEventListener('click', abort);

// abortable actions
await someAction();
if (signal.aborted) throw Error('Aborted');
await otherAction(signal);
```

**Comment by broofa** [comment]
Editorial: The distinction between `AbortController` and `AbortSignal` feels overly contrived to me.    I get (assume) this pattern is meant to separate the concerns of "signal that can be aborted" from "thing doing the aborting", which I agree may be important at times.  However, most (all!) of the use cases I care about this isn't really a big concern.  Thus, having to deal with the controller-signal distinction is mostly just an annoyance I'd rather do without.   Allowing for this form of destructuring would alleviate some of that pain.

**Comment by annevk** [comment]
This is how all instance methods in the platform behave and changing this would require changing IDL, as far as I know. I somewhat doubt there is appetite for that. There was some kind of JavaScript proposal at one point for automatic/easier bind.

**Comment by broofa** [comment]
How does one reconcile the fact that same argument could be made for [the Console Standard](https://console.spec.whatwg.org/), yet...
```javascript
const log = console.log;
log('hello world');
```
... works everywhere?

**Comment by domenic** [comment]
There are no instances of `console`; it's just a namespace, with only one `log` method per global. There are many instances of `AbortController` that need to all use prototypes to share the same method.

**Comment by broofa** [comment]
Thanks for the quick replies and the explanations here.   I do appreciate the time and effort you folks put into these standards.

That said, having made an earnest attempt to use this API I ended up going with the following utility method.  It's just easier / simpler to use... unfortunately.

```javascript
function createAbortable() {
  const signal = { aborted: false };

  return {
    signal,
    abort: () => {
      signal.aborted = true;
    }
  };
}
```

Read into this what you will, I guess.  🤷

**Comment by annevk** [comment]
Except that it won't interoperate with web platform APIs? I'm not sure why you closed this, but I could see offering a static that offers the functionality you're after, though ideally we'd do some research first to see if it's a common pattern.

**Comment by annevk** [comment]
I think with 2 you are overstating your case as there is a reason to separate these two, though perhaps the revealing constructor pattern could have been used instead. I forgot how we ended up with the current design.

**Comment by bathos** [comment]
> flawed construct for it's intended purpose

The API seems to cover more than one use case and control flow pattern. Separation of the controller and signal allows sharing the signal with code that supports reacting to the abort event / observing the aborted status even when that code shouldn't also have control over whether or when the signal aborts. In cases where the consumer of the signal should be able to control aborting, well - that's when you pass the _controller_ instead of the signal alone.

We use AbortController/AbortSignal a ton but it's very rare that we pass controllers around. I only turned up one instance of sharing a controller just now out of hundreds of usages of AC/AS. So while we likely have different most-common-needs, it does not seem accurate to me to say the current model is flawed: it meets our needs and your suggested change would not.

I agree that utilities for common AC/AS usage patterns would be fantastic though - to me it seems that's the underlying issue, maybe? AC/AS provide the control flow primitives, but the API surface isn't specifically optimized for any of them in particular, so e.g. in your case it ends up seeming overly complex, while in our case it tends to demand a lot of explicit wiring-up. At this point we have a pretty extensive set of helper functions for working with signals (e.g. `await race(signal, promise)` potentially rejects w/ AbortError DOMException) and I suspect many of them are things people end up reinventing over and over right now.

**Comment by annevk** [comment]
Anything we do will have to be backwards compatible. I vaguely wonder if we should add this:
```js
const signal = new AbortSignal(abort => {
  $('#someButton').addEventListener('click', abort);
});
@jakearchibald @domenic do you remember why we went with an explicit `AbortController` object?

**Comment by annevk** [comment]
Thanks for writing that up @jakearchibald! Do you find you need to "break out" with the `Promise` constructor as well? Anyway, it seems like more justification is needed here before considering new wrappers of sorts.

**Comment by jakearchibald** [comment]
> Do you find you need to "break out" with the `Promise` constructor as well?

Very occasionally, but not often. The last time I remember doing it was to create the "abort the current operation in favour of a new operation" before we had `AbortController`:

```js
let currentJob = Promise.resolve();
let currentReject;

function showSearchResults(input) {
  if (currentReject) currentReject(new DOMException('', 'AbortError'));
  const abortPromise = new Promise((_, reject) => {
    currentReject = reject;
  });

  return currentJob = currentJob.catch(() => {}).then(() => {
    return Promise.race([
      abortPromise,
      Promise.resolve().then(async () => {
        // …do stuff…
      }),
    ]);
  });
}
```

But I've since rewritten that code to just use `AbortController`.

**Comment by broofa** [comment]
First, let me apologize for my "flawed" comment (😳).  That came across a bit sharper than intended.   And I'll be the first to acknowledge that the `{signal, abort}` tuple I've proposed  is basically the same thing as AC, the only difference being that it doesn't carry the weighty formality of a class, and has `abort` well and truly bound to `signal`.  So it's not like I'm offering a complete redesign here.  Anyhow... sorry about that.

> details on the history here

@jakearchibald : Thanks for the link to the previous discussion(s).    I was sure such discussion existed but wasn't sure where.   I'm afraid I don't have time to read through that in detail at the moment, but I'll try to catch up on it later (maybe this weekend?)

> This is an antipattern. It means abort is being called with an Event object

Having been bitten by [Firefox's lateness argument](http://benalman.com/news/2009/07/the-mysterious-firefox-settime/) back in the day, I appreciate this concern I question whether this is something WHATWG should be policing, though.   If a user is concerned with this, `() => abort()` works.

I think @bathos has the right path forward here.  Treat AC/AS as the control flow primitives and build utilities on top of that.

**Comment by jakearchibald** [comment]
I'm really interested in ways we can make this stuff easier to use btw! I'm still keen on the second idea in https://github.com/whatwg/dom/issues/946#issuecomment-775093185, but it seems that conversation fizzled out.

> If a user is concerned with this, `() => abort()` works.

But now we're talking about a big API change just to make it `() => abort()` rather than `() => controller.abort()`, and I don't see a ton of value there.

**Comment by bathos** [comment]
@jakearchibald fwiw I think the doAbortable model shown in that thread is, at best, moving an existing problem around. The need is to “decorate await”, not to “decorate async”, and it would probably not be great to encourage the latter. That is, usually every interleaving point / control yield would want to “race the signal”. This is always going to be awkward, but the awkwardness can be minimized. I mentioned the `race` util we use in particular for this reason — it’s the “building block” of all the signal patterns we’ve found/needed to date.

I would love to see `signal.race(Promise<any> p)` become native. Once you’re always racing the signal, you get to use catch/finally just like in any other sync or async function. I believe some form of `race`+`isAbortError` would be the minimal API needd to fix the “syntax gap”.

**Comment by jakearchibald** [comment]
@bathos mind posting that in the other thread to keep the discussion in one place?

**Comment by benjamingr** [comment]
I just want to add I agree with Domenic's and Anne's sentiments here regarding it being weird if only AbortController had a bound `abort` method.

I also want to add that creating `AbortController`s in code is a lot more rare (once, when flows start and once when flows fork) than passing AbortSignals in (which happens very often).

**Comment by Jamesernator** [comment]
> > Do you find you need to "break out" with the `Promise` constructor as well?

I've personally used it quite a few times in particular for concurrency management, e.g. locks, (async) task queues, etc etc.

A typical example would be something like lock:

```js
class Deferred {
  resolve;
  reject;
  promise = new Promise((resolve, reject) => {
    this.resolve = resolve;
    this.reject = reject;
  });
}

class Lock {
  #locked = false;
  #pendingRequests = [];
  
  #release = () => {
    assert(this.#locked);
    const firstPending = this.#pendingRequests.shift();
    if (firstPending) {
      firstPending.resolve(once(this.#release));
    } else {
      this.#locked = false;
    }
  }
  
  async acquire() {
    if (this.#locked) {
      const deferred = new Deferred();
      this.#pendingRequests.push(deferred);
      return await deferred.promise;
    }
    this.#locked = true;
    return once(this.#release);
  }
}
```

---

Although I can say one place I have specifically wanted the revealing constructor pattern on `AbortSignal` is to be able to subclass `AbortSignal`, which is otherwise undoable as `AbortSignal` has to be tied to a controller (so `super()` always throws, as `new AbortSignal()` always throws). It might be doable by some awful `super` override hacks, but real subclassing would be a lot nicer.

Although I wouldn't even need the subclass (actually a parallel implementation + extra methods) if a [few](https://github.com/whatwg/dom/issues/951) [suggestions](https://github.com/whatwg/dom/issues/948) [were](https://github.com/whatwg/dom/issues/946) [all](https://github.com/whatwg/dom/issues/920) [added](https://github.com/whatwg/dom/issues/927), the only reason I have the parallel implementation is that the listed issues are basically all things I use heavily when working with `AbortSignal` so it's just too cumbersome not to have them consistently available.
